name: Backup Fork and Sync

on:
  schedule:
    - cron: '0 0 * * 0'  # 每週日午夜運行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  backup-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 獲取所有歷史記錄和標籤

      - name: List all branches
        id: list_branches
        run: |
          git fetch --all
          git branch -r | grep -v '\->' | grep 'upstream/' | sed 's/upstream\///' > branches.txt
          echo "branches=$(cat branches.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/nextfoam/nextfoam-cfd.git
          git fetch upstream

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Backup and sync each branch
        run: |
          for branch in $(echo "${{ steps.list_branches.outputs.branches }}"); do
            git checkout $branch || git checkout -b $branch upstream/$branch
            git merge upstream/$branch || echo "No changes to merge or merge conflict"
            git push origin $branch || echo "Failed to push $branch to origin"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create version tag
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          git tag -a "sync-$TIMESTAMP" -m "Sync on $TIMESTAMP"
          git push --tags origin || echo "Failed to push tags to origin"

      - name: Check for errors
        if: failure()
        run: |
          echo "Workflow failed. Please check the logs for more information."
